const nextJest = require('next/jest');

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files
  dir: './',
});

// Add any custom config to be passed to Jest
const customJestConfig = {
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  testEnvironment: 'jsdom',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@/components/(.*)$': '<rootDir>/src/components/$1',
    '^@/lib/(.*)$': '<rootDir>/src/lib/$1',
    '^@/utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@/hooks/(.*)$': '<rootDir>/src/hooks/$1',
    '^@/types/(.*)$': '<rootDir>/src/types/$1',
    '^@/services/(.*)$': '<rootDir>/src/services/$1',
    '^@/config/(.*)$': '<rootDir>/src/config/$1',
    '^@/styles/(.*)$': '<rootDir>/src/styles/$1',
    '^@/tests/(.*)$': '<rootDir>/tests/$1',
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/tests/__mocks__/fileMock.js',
  },
  testPathIgnorePatterns: [
    '<rootDir>/.next/',
    '<rootDir>/node_modules/',
    '<rootDir>/out/',
    '<rootDir>/dist/',
  ],
  collectCoverageFrom: [
    'src/**/*.{js,jsx,ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/*.stories.{js,jsx,ts,tsx}',
    '!src/**/*.test.{js,jsx,ts,tsx}',
    '!src/**/*.spec.{js,jsx,ts,tsx}',
    '!src/**/index.{js,jsx,ts,tsx}',
    '!src/**/types.{js,jsx,ts,tsx}',
    '!src/**/constants.{js,jsx,ts,tsx}',
    '!src/**/styles.{js,jsx,ts,tsx}',
    '!src/**/tailwind.config.{js,jsx,ts,tsx}',
    '!src/**/next.config.{js,jsx,ts,tsx}',
    '!src/**/jest.config.{js,jsx,ts,tsx}',
    '!src/**/jest.setup.{js,jsx,ts,tsx}',
    '!src/**/postcss.config.{js,jsx,ts,tsx}',
    '!src/**/eslint.config.{js,jsx,ts,tsx}',
    '!src/**/prettier.config.{js,jsx,ts,tsx}',
    '!src/**/babel.config.{js,jsx,ts,tsx}',
    '!src/**/webpack.config.{js,jsx,ts,tsx}',
    '!src/**/rollup.config.{js,jsx,ts,tsx}',
    '!src/**/vite.config.{js,jsx,ts,tsx}',
    '!src/**/parcel.config.{js,jsx,ts,tsx}',
    '!src/**/metro.config.{js,jsx,ts,tsx}',
    '!src/**/craco.config.{js,jsx,ts,tsx}',
    '!src/**/config-overrides.{js,jsx,ts,tsx}',
    '!src/**/setupProxy.{js,jsx,ts,tsx}',
    '!src/**/setupTests.{js,jsx,ts,tsx}',
    '!src/**/testUtils.{js,jsx,ts,tsx}',
    '!src/**/testHelpers.{js,jsx,ts,tsx}',
    '!src/**/testData.{js,jsx,ts,tsx}',
    '!src/**/testMocks.{js,jsx,ts,tsx}',
    '!src/**/testSetup.{js,jsx,ts,tsx}',
    '!src/**/testConfig.{js,jsx,ts,tsx}',
    '!src/**/testEnvironment.{js,jsx,ts,tsx}',
    '!src/**/testGlobals.{js,jsx,ts,tsx}',
    '!src/**/testMatchers.{js,jsx,ts,tsx}',
    '!src/**/testTransformers.{js,jsx,ts,tsx}',
    '!src/**/testReporters.{js,jsx,ts,tsx}',
    '!src/**/testCoverage.{js,jsx,ts,tsx}',
    '!src/**/testThresholds.{js,jsx,ts,tsx}',
    '!src/**/testWatch.{js,jsx,ts,tsx}',
    '!src/**/testDebug.{js,jsx,ts,tsx}',
    '!src/**/testPerformance.{js,jsx,ts,tsx}',
    '!src/**/testAccessibility.{js,jsx,ts,tsx}',
    '!src/**/testE2E.{js,jsx,ts,tsx}',
    '!src/**/testIntegration.{js,jsx,ts,tsx}',
    '!src/**/testUnit.{js,jsx,ts,tsx}',
    '!src/**/testSnapshot.{js,jsx,ts,tsx}',
    '!src/**/testVisual.{js,jsx,ts,tsx}',
    '!src/**/testContract.{js,jsx,ts,tsx}',
    '!src/**/testMutation.{js,jsx,ts,tsx}',
    '!src/**/testQuery.{js,jsx,ts,tsx}',
    '!src/**/testSubscription.{js,jsx,ts,tsx}',
    '!src/**/testWebSocket.{js,jsx,ts,tsx}',
    '!src/**/testSocket.{js,jsx,ts,tsx}',
    '!src/**/testRealTime.{js,jsx,ts,tsx}',
    '!src/**/testLive.{js,jsx,ts,tsx}',
    '!src/**/testStream.{js,jsx,ts,tsx}',
    '!src/**/testEvent.{js,jsx,ts,tsx}',
    '!src/**/testMessage.{js,jsx,ts,tsx}',
    '!src/**/testNotification.{js,jsx,ts,tsx}',
    '!src/**/testAlert.{js,jsx,ts,tsx}',
    '!src/**/testToast.{js,jsx,ts,tsx}',
    '!src/**/testModal.{js,jsx,ts,tsx}',
    '!src/**/testDialog.{js,jsx,ts,tsx}',
    '!src/**/testPopover.{js,jsx,ts,tsx}',
    '!src/**/testTooltip.{js,jsx,ts,tsx}',
    '!src/**/testDropdown.{js,jsx,ts,tsx}',
    '!src/**/testMenu.{js,jsx,ts,tsx}',
    '!src/**/testTabs.{js,jsx,ts,tsx}',
    '!src/**/testAccordion.{js,jsx,ts,tsx}',
    '!src/**/testCarousel.{js,jsx,ts,tsx}',
    '!src/**/testSlider.{js,jsx,ts,tsx}',
    '!src/**/testProgress.{js,jsx,ts,tsx}',
    '!src/**/testSpinner.{js,jsx,ts,tsx}',
    '!src/**/testSkeleton.{js,jsx,ts,tsx}',
    '!src/**/testLoading.{js,jsx,ts,tsx}',
    '!src/**/testError.{js,jsx,ts,tsx}',
    '!src/**/testEmpty.{js,jsx,ts,tsx}',
    '!src/**/testNotFound.{js,jsx,ts,tsx}',
    '!src/**/testUnauthorized.{js,jsx,ts,tsx}',
    '!src/**/testForbidden.{js,jsx,ts,tsx}',
    '!src/**/testServerError.{js,jsx,ts,tsx}',
    '!src/**/testBadRequest.{js,jsx,ts,tsx}',
    '!src/**/testConflict.{js,jsx,ts,tsx}',
    '!src/**/testUnprocessable.{js,jsx,ts,tsx}',
    '!src/**/testTooManyRequests.{js,jsx,ts,tsx}',
    '!src/**/testServiceUnavailable.{js,jsx,ts,tsx}',
    '!src/**/testGatewayTimeout.{js,jsx,ts,tsx}',
    '!src/**/testInternalServerError.{js,jsx,ts,tsx}',
    '!src/**/testNotImplemented.{js,jsx,ts,tsx}',
    '!src/**/testBadGateway.{js,jsx,ts,tsx}',
    '!src/**/testRequestTimeout.{js,jsx,ts,tsx}',
    '!src/**/testGone.{js,jsx,ts,tsx}',
    '!src/**/testLengthRequired.{js,jsx,ts,tsx}',
    '!src/**/testPreconditionFailed.{js,jsx,ts,tsx}',
    '!src/**/testRequestEntityTooLarge.{js,jsx,ts,tsx}',
    '!src/**/testRequestUriTooLong.{js,jsx,ts,tsx}',
    '!src/**/testUnsupportedMediaType.{js,jsx,ts,tsx}',
    '!src/**/testRequestedRangeNotSatisfiable.{js,jsx,ts,tsx}',
    '!src/**/testExpectationFailed.{js,jsx,ts,tsx}',
    '!src/**/testUnprocessableEntity.{js,jsx,ts,tsx}',
    '!src/**/testLocked.{js,jsx,ts,tsx}',
    '!src/**/testFailedDependency.{js,jsx,ts,tsx}',
    '!src/**/testUpgradeRequired.{js,jsx,ts,tsx}',
    '!src/**/testPreconditionRequired.{js,jsx,ts,tsx}',
    '!src/**/testTooManyRequests.{js,jsx,ts,tsx}',
    '!src/**/testRequestHeaderFieldsTooLarge.{js,jsx,ts,tsx}',
    '!src/**/testUnavailableForLegalReasons.{js,jsx,ts,tsx}',
    '!src/**/testInternalServerError.{js,jsx,ts,tsx}',
    '!src/**/testNotImplemented.{js,jsx,ts,tsx}',
    '!src/**/testBadGateway.{js,jsx,ts,tsx}',
    '!src/**/testServiceUnavailable.{js,jsx,ts,tsx}',
    '!src/**/testGatewayTimeout.{js,jsx,ts,tsx}',
    '!src/**/testHttpVersionNotSupported.{js,jsx,ts,tsx}',
    '!src/**/testVariantAlsoNegotiates.{js,jsx,ts,tsx}',
    '!src/**/testInsufficientStorage.{js,jsx,ts,tsx}',
    '!src/**/testLoopDetected.{js,jsx,ts,tsx}',
    '!src/**/testNotExtended.{js,jsx,ts,tsx}',
    '!src/**/testNetworkAuthenticationRequired.{js,jsx,ts,tsx}',
  ],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  testMatch: [
    '<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}',
    '<rootDir>/src/**/*.{test,spec}.{js,jsx,ts,tsx}',
    '<rootDir>/tests/**/*.{test,spec}.{js,jsx,ts,tsx}',
  ],
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { presets: ['next/babel'] }],
  },
  transformIgnorePatterns: [
    '/node_modules/',
    '^.+\\.module\\.(css|sass|scss)$',
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  testEnvironmentOptions: {
    url: 'http://localhost',
  },
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/tsconfig.jest.json',
    },
  },
  verbose: true,
  clearMocks: true,
  restoreMocks: true,
  resetMocks: true,
  testTimeout: 10000,
  maxWorkers: '50%',
  bail: 1,
  detectOpenHandles: true,
  forceExit: true,
};

// createJestConfig is exported this way to ensure that next/jest can load the Next.js config which is async
module.exports = createJestConfig(customJestConfig);
